### PR TITLE
Adding note about I/we/you

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by lexnederbragt** [comment]
Thanks! Do you know whether there is a (scientific) reference for this 'approach to knowledge transfer'?

**Comment by gvwilson** [comment]
Jargon is "gradual release of responsibility": https://en.wikipedia.org/wiki/Gradual_release_of_responsibility - I've found several references to "Fisher & Frey", but haven't read any of their papers.

**Comment by lexnederbragt** [comment]
Maybe we could use "Better Learning Through Structured Teaching: A Framework for the Gradual Release of Responsibility", 2nd edition, Douglas Fisher & Nancy Frey 2013, ISBN 978-1-4166-1830-0 as reference?

**Comment by lexnederbragt** [comment]
Merging now, will add the reference right afterwards.

**Pull request merged**
